Ike/wcv2
thirdweb-dev/js pull request #1215
Opened 2023-06-21 16:42 UTC by iketw

2023-06-23 18:16 UTC, iketw commented
./release-pr

2023-06-26 14:54 UTC, MananTank commented on .changeset/sour-dingos-taste.md
> +"@thirdweb-dev/wallets": major
Doesn't that also bump the `@thirdweb-dev/react` to major version?

2023-06-26 17:24 UTC, MananTank commented
/release-pr

2023-06-27 13:20 UTC, hixus commented
Thirdweb mobile sdk user here. Noticed this now and would like is there some beta npm packages or what is the expected  migration path if this comes at the same time as wc 1 is shutdown?

2023-06-27 13:37 UTC, iketw commented
./release-pr

2023-06-27 14:04 UTC, iketw commented
> Thirdweb mobile sdk user here. Noticed this now and would like is there some beta npm packages or what is the expected migration path if this comes at the same time as wc 1 is shutdown? We did some of the changes manually so wc2 somewhat works.

Hi @hixus , we are releasing our updated packages later today. The updates deprecate wcv1 and migrates wallets to use wcv2. For React Native specifically you shouldn't see any API changes, you should be able to use Rainbow and MM the same way, it will just use WCV2 in the background. 

If you want to test the package we'll release, you can get it here: `@thirdweb-dev/react-native@0.0.0-dev-c4fbd0b-20230627134115`

Feel free to ask any other questions, we know this migration is stressful

2023-06-27 16:04 UTC, MananTank commented
/release-pr

2023-06-27 19:11 UTC, MananTank commented
/release-pr

2023-06-27 23:33 UTC, iketw commented
./release-pr

2023-06-27 23:49 UTC, jnsdls commented on packages/wallets/package.json
> +  "resolutions": {
resolutions on the package-level don't do anything with `pnpm` @iketw @MananTank - if you *need* these resolutions you will have to put them in the root package.json

2023-06-27 23:49 UTC, jnsdls commented on packages/wallets/package.json
> +  "resolutions": {
(if you update your pnpm version to latest it will also warn you about this)

2023-06-27 23:50 UTC, jnsdls requested changes

2023-06-27 23:50 UTC, jnsdls commented on .changeset/sour-dingos-taste.md
> +[RN/Wallets/React] Migrate wallets to WCV2 and remove WCV1 support
can we not do this `[RN/Wallets/React]` stuff? it already puts this changeset in every package when it gets released based on the above metadata of which packages changed how

2023-06-27 23:50 UTC, jnsdls commented on .changeset/sour-dingos-taste.md
> +[RN/Wallets/React] Migrate wallets to WCV2 and remove WCV1 support
do it in PR titles sure but not in the changeset, unnecessary to do so

2023-06-28 00:04 UTC, jnsdls approved these changes

2023-06-28 00:06 UTC, merged