fix: Added 50k overhead to userOps estimation
thirdweb-dev/js pull request #2677
Opened 2024-04-03 20:04 UTC by farhanW3

2024-04-03 20:15 UTC, joaquim-verges requested changes
test caught an issue here

2024-04-03 20:15 UTC, joaquim-verges commented on legacy_packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts
> +    partialOp.callGasLimit = partialOp.callGasLimit.add(50_000);
you need to do this in diff places depending on the path here.

line 284
line 299
line 327

2024-04-03 20:15 UTC, joaquim-verges commented on packages/thirdweb/src/wallets/smart/lib/userop.ts
> +  partialOp.callGasLimit = partialOp.callGasLimit + 50_000n;
same here - there's diff path including one that needs to re-sign the payload from the paymaster

2024-04-03 20:16 UTC, 0xFirekeeper approved these changes

2024-04-03 20:18 UTC, joaquim-verges requested changes

2024-04-03 20:18 UTC, joaquim-verges commented on legacy_packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts
> +        partialOp.callGasLimit = BigNumber.from(estimates.callGasLimit).add(
missing one case line 284

2024-04-03 20:18 UTC, joaquim-verges commented on packages/thirdweb/src/wallets/smart/lib/userop.ts
> +      partialOp.callGasLimit = estimates.callGasLimit + 50_000n;
missing one case line 113.

also can you remove `(following same as unity-sdk)` please

2024-04-05 00:20 UTC, joaquim-verges approved these changes

2024-04-05 00:22 UTC, merged