joaquim/rn-connect-ui-2
thirdweb-dev/js pull request #3438
Opened 2024-06-21 14:31 UTC by joaquim-verges

## Problem solved

Short description of the bug fixed or feature added

## Changes made

- [ ] Public API changes: list the public API changes made if any
- [ ] Internal API changes: explain the internal logic changes

## How to test

- [ ] Automated tests: link to unit test file
- [ ] Manual tests: step by step instructions on how to test

## Contributor NFT

Paste in your wallet address below and we will airdrop you a special NFT when your pull request is merged. 

```Address: ```

2024-06-21 14:31 UTC, joaquim-verges commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/3438?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3438** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/3438?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#3246** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/3246?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @joaquim-verges and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-01 16:30 UTC, jnsdls requested changes

2024-07-01 16:30 UTC, jnsdls commented on packages/thirdweb/src/react/native/ui/components/Address.tsx
> +  }, [copySuccess]);
have to clean up this timeout if it was set in the cleanup function

2024-07-01 16:30 UTC, jnsdls commented on packages/thirdweb/src/react/native/ui/components/Address.tsx
> +        // @ts-ignore - missing native types
prefer `@ts-expect-error`

```suggestion
        // @ts-expect-error - missing native types
```

2024-07-01 16:30 UTC, jnsdls commented on packages/thirdweb/src/react/native/ui/components/WalletImage.tsx
> +      }
just keep this entirely outside of the useQuery, it doesn't need to be in here

2024-07-01 16:30 UTC, jnsdls commented on packages/thirdweb/src/react/native/ui/components/WalletImage.tsx
> +      ensAvatar,
remove

2024-07-01 16:30 UTC, jnsdls commented on packages/thirdweb/src/react/native/ui/connect/ConnectedButton.tsx
> +            {balanceQuery.data?.symbol}{" "}
why the ending space? `{" "}`

2024-07-01 16:30 UTC, jnsdls commented on packages/thirdweb/src/react/native/ui/connect/ConnectedButton.tsx
> +              : "---"}{" "}
is the `---` the "loading" state?

2024-07-01 16:30 UTC, jnsdls commented on packages/thirdweb/src/react/native/ui/connect/TokenListScreen.tsx
> +    <>
empty fragment?

2024-07-01 20:12 UTC, merged