chore(wallet-ui): initialize project
thirdweb-dev/js pull request #3477
Opened 2024-06-24 23:26 UTC by gregfromstl

## Problem solved

Short description of the bug fixed or feature added

## Changes made

- [ ] Public API changes: list the public API changes made if any
- [ ] Internal API changes: explain the internal logic changes

## How to test

- [ ] Automated tests: link to unit test file
- [ ] Manual tests: step by step instructions on how to test

## Contributor NFT

Paste in your wallet address below and we will airdrop you a special NFT when your pull request is merged. 

```Address: ```

2024-06-24 23:27 UTC, gregfromstl commented
* **#3477** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/3477?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gregfromstl and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-28 22:27 UTC, jnsdls requested changes
couple of things and then also update the favicon (we're not vercel)

2024-06-28 22:27 UTC, jnsdls commented on apps/wallet-ui/README.md
> +
I was trying to `README` but it was empty

2024-06-28 22:27 UTC, jnsdls commented on apps/wallet-ui/biome.json
> +  },
I _believe_ this is the same as `linter:true`?

2024-06-28 22:27 UTC, jnsdls commented on apps/wallet-ui/package.json
> +  "name": "wallet-ui",
make sure to also add this to the `ignore` in the changesets config file

2024-06-28 22:27 UTC, jnsdls commented on apps/wallet-ui/src/app/[ecosystem]/layout.tsx
> +export default function Layout() {}
shouldn't add empty files

2024-06-28 22:27 UTC, jnsdls commented on pnpm-lock.yaml
> +  tailwindcss@3.4.4(ts-node@10.9.2(@types/node@20.14.6)(typescript@5.5.2)):
suspicious, do we have different versions of tailwind installed now - if so lets align them

2024-06-28 23:24 UTC, jnsdls approved these changes

2024-06-28 23:46 UTC, merged