fix(connect-ui): update Connect UI tabs styling with new design enhancements
thirdweb-dev/js pull request #3746
Opened 2024-07-18 20:25 UTC by gregfromstl

## Problem solved

Short description of the bug fixed or feature added

## Changes made

- [ ] Public API changes: list the public API changes made if any
- [ ] Internal API changes: explain the internal logic changes

## How to test

- [ ] Automated tests: link to unit test file
- [ ] Manual tests: step by step instructions on how to test

## Contributor NFT

Paste in your wallet address below and we will airdrop you a special NFT when your pull request is merged. 

```Address: ```

2024-07-18 20:51 UTC, joaquim-verges approved these changes

2024-07-18 22:56 UTC, MananTank commented
Need to make these buttons full-width: 
<img width="469" alt="image" src="https://github.com/user-attachments/assets/50867ede-e702-44fd-9484-e744c4ac4ccf">

2024-07-18 22:56 UTC, MananTank submitted a review, later dismissed
Fix purchases tab button width

2024-07-19 16:38 UTC, MananTank approved these changes

2024-07-19 16:55 UTC, MananTank requested changes
<img width="451" alt="image" src="https://github.com/user-attachments/assets/05a26666-4021-40dc-af22-5f6a2da65249">

Need to fix styles in light mode

2024-07-19 16:57 UTC, MananTank commented on packages/thirdweb/src/react/web/ui/components/Tabs.tsx
>            <button
Prefer using `Button` component here

2024-07-19 17:06 UTC, MananTank commented on packages/thirdweb/src/react/web/ui/components/Tabs.tsx
> +                  ? `0px 0px 10px ${theme.colors.modalBg}`
Can we remove this shadow? We are not using shadows anywhere else - so this stands out too much

2024-07-19 18:52 UTC, MananTank approved these changes

2024-07-19 19:18 UTC, merged