Add prebuilt component: StakeERC721Button
thirdweb-dev/js pull request #3884
Opened 2024-07-31 03:15 UTC by kien-ngo

2024-08-01 20:22 UTC, gregfromstl requested changes
Mainly just curious what `erc20Value` is for and if there's a way we can avoid modifying the extension options

2024-08-01 20:22 UTC, gregfromstl commented on packages/thirdweb/src/extensions/erc721/__generated__/IStaking721/read/stakingToken.ts
> +export async function stakingToken(options: BaseTransactionOptions) {
Changeset for this

2024-08-01 20:22 UTC, gregfromstl commented on packages/thirdweb/src/extensions/modular/__generated__/BatchMetadataERC1155/write/uploadMetadata.ts
> +    erc20Value: async () => (await asyncOptions()).overrides?.erc20Value,
What are these for? Also were these added via the generation script or manual? I can't find the diff for the generation script

2024-08-02 17:42 UTC, kien-ngo commented
closing this for now, need to rethink the design

2024-08-02 17:42 UTC, closed without merging