Dashboard v5: Aug 08 run
thirdweb-dev/js pull request #3998
Opened 2024-08-08 06:19 UTC by kien-ngo

2024-08-09 00:45 UTC, kien-ngo commented
damn... should have broken this down to smaller chunk

2024-08-09 01:16 UTC, kien-ngo commented
Ok close. Just need 2 missing extensions: setTokenURI for ERC721 and 1155
Not the generated one

2024-08-11 18:42 UTC, jnsdls requested changes

2024-08-11 18:42 UTC, jnsdls commented on diff
> +diff --git a/packages/thirdweb/src/extensions/erc721/write/updateTokenURI.ts b/packages/thirdweb/src/extensions/erc721/write/updateTokenURI.ts
probably didn't mean to check this in?

2024-08-11 21:12 UTC, kien-ngo commented on diff
> +diff --git a/packages/thirdweb/src/extensions/erc721/write/updateTokenURI.ts b/packages/thirdweb/src/extensions/erc721/write/updateTokenURI.ts
Omg how it got in here xD

2024-08-12 23:57 UTC, jnsdls approved these changes

2024-08-13 01:03 UTC, merged