update-deploy-form-header
thirdweb-dev/js pull request #4016
Opened 2024-08-08 23:57 UTC by MananTank

## Problem solved

Short description of the bug fixed or feature added

2024-08-08 23:57 UTC, MananTank commented
* **#4017** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4017?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4016** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4016?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-09 00:35 UTC, jnsdls requested changes

2024-08-09 00:35 UTC, jnsdls commented on apps/dashboard/src/@/lib/shareLink.ts
> +    toast.success("URL copied to clipboard");
`success` feels too much here - this is less a success and more a "info" level thing, can be a bit more neutral imo

2024-08-09 00:35 UTC, jnsdls commented on apps/dashboard/src/components/share-buttom/index.tsx
> +      toast.success("URL copied to clipboard");
same, `success` seems too much here

2024-08-09 17:30 UTC, jnsdls approved these changes

2024-08-09 17:36 UTC, merged