feat(native): add passkey support and improve wallet connection handling
thirdweb-dev/js pull request #4077
Opened 2024-08-13 11:03 UTC by joaquim-verges

## Problem solved

Short description of the bug fixed or feature added

2024-08-13 11:04 UTC, joaquim-verges commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4077?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4077** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4077?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4022** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4022?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @joaquim-verges and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-13 18:09 UTC, jnsdls requested changes
somehow broke size limit & thirdweb www build with these changes

2024-08-14 03:13 UTC, joaquim-verges commented
> somehow broke size limit & thirdweb www build with these changes

Should be good now @jnsdls

2024-08-14 03:15 UTC, jnsdls approved these changes

2024-08-14 20:01 UTC, merged