Update
thirdweb-dev/js pull request #4128
Opened 2024-08-16 06:56 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-08-16 06:56 UTC, kien-ngo commented
* **#4128** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4128?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-16 20:43 UTC, jnsdls requested changes

2024-08-16 20:43 UTC, jnsdls commented on packages/thirdweb/src/exports/utils.ts
> +export { max } from "../utils/bigint.js";
what about `min()` :(

2024-08-16 20:43 UTC, jnsdls commented on apps/dashboard/src/contract-ui/tabs/listings/components/listing-stats.tsx
> +  const _totalListings = useMemo(
```suggestion
  const combinedListingCount = useMemo(
```

2024-08-16 20:43 UTC, jnsdls commented on apps/dashboard/src/contract-ui/tabs/overview/components/MarketplaceDetails.tsx
> +        max((countQuery?.data || 3n) - 3n, BigInt(Number.MAX_SAFE_INTEGER)),
nice!

2024-08-17 04:59 UTC, kien-ngo commented on packages/thirdweb/src/exports/utils.ts
> +export { max } from "../utils/bigint.js";
oh lol

2024-08-19 19:30 UTC, jnsdls approved these changes

2024-08-19 21:10 UTC, merged