[Dashboard] envs clean-up
thirdweb-dev/js pull request #4170
Opened 2024-08-18 23:06 UTC by kien-ngo

- [x] Remove a lof of duplicated instances of `ThirdwebClient` & env variables across multiple files
- [ ] There's only 1 main ThirdwebClient from now on which can be imported from `lib/thirdweb-client`. It can switch between clientId and secretKey depends on the environment
- [ ] All env variables like `DASHBOARD_THIRDWEB_CLIENT_ID`, `DASHBOARD_THIRDWEB_SECRET_KEY`, `isProd` etc. now live inside `@/constants/env`

2024-08-18 23:12 UTC, joaquim-verges approved these changes

2024-08-19 19:56 UTC, jnsdls requested changes

2024-08-19 19:56 UTC, jnsdls commented on apps/dashboard/src/lib/thirdweb-client.ts
> +import {
removing the duplication here makes sense but can we move it the *opposite* direction? I'd like to keep `@constants/client` and remove this file instead.

2024-08-19 19:56 UTC, jnsdls commented on apps/dashboard/src/lib/thirdweb-client.ts
> +import {
maybe even `@/client`

2024-08-19 20:48 UTC, jnsdls requested changes

2024-08-19 20:48 UTC, jnsdls commented on apps/dashboard/src/contract-ui/tabs/overview/components/MarketplaceDetails.tsx
> +import { thirdwebClient } from "../../../../@/constants/client";
fix import url


```suggestion
import { thirdwebClient } from "@/constants/client";
```

2024-08-19 20:48 UTC, jnsdls commented on apps/dashboard/src/lib/ens.ts
> +import { thirdwebClient } from "../@/constants/client";
absolute path pls


```suggestion
import { thirdwebClient } from "@/constants/client";
```

2024-08-19 22:01 UTC, jnsdls approved these changes

2024-08-20 08:06 UTC, merged