Add useHookAtTopLevel rule in biome and fix lint errors
thirdweb-dev/js pull request #4213
Opened 2024-08-20 17:45 UTC by MananTank

## Problem solved

Short description of the bug fixed or feature added

2024-08-20 17:45 UTC, MananTank commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4213?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4213** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4213?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4211** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4211?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-20 17:46 UTC, jnsdls requested changes
missing changeset

2024-08-20 18:04 UTC, jnsdls approved these changes

2024-08-21 02:36 UTC, joaquim-verges approved these changes

2024-08-21 09:11 UTC, merged