smart wallet dev tests
thirdweb-dev/js pull request #4226
Opened 2024-08-21 02:27 UTC by joaquim-verges

## Problem solved

Short description of the bug fixed or feature added

2024-08-21 02:27 UTC, joaquim-verges commented
* **#4226** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4226?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @joaquim-verges and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-21 17:14 UTC, jnsdls requested changes
breaks docs - @MananTank can we figure out a way to exclude `*.test.*` files from typedoc? Its typedoc that is picking up test files and failing on them always

2024-08-21 18:15 UTC, MananTank commented
We can only tell the typedoc to ignore the tests as an entrypoint - but it will still require the tsc compilation to succeed 

https://typedoc.org/options/input/#exclude

I've pushed the ts fix though - the docs should build now

2024-08-22 04:41 UTC, jnsdls approved these changes

2024-08-22 05:00 UTC, merged