[Dashboard] Remove VStack - Need test so do not merge
thirdweb-dev/js pull request #4727
Opened 2024-09-20 18:34 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

---

## PR-Codex overview
The focus of this PR is to replace the `VStack` components with `div` elements in multiple files for better styling and layout control.

### Detailed summary
- Replaced `VStack` with `div` in `OnboardingTitle`, `JudgesEarn`, `AvatarShowcase`, and more components for styling.
- Updated import statements for `Flex` and `SimpleGrid` in `JudgesEarn` and `Judges` components.
- Replaced `VStack` with `div` in `ReceiveFundsModal`, `UploadStep`, and more components for consistent styling.
- Removed `VStack` import in `BillingPeriod` and `OnboardingGeneral` components.

> The following files were skipped due to too many changes: `apps/dashboard/src/components/onboarding/Steps.tsx`, `apps/dashboard/src/components/settings/Account/AccountForm.tsx`, `apps/dashboard/src/components/settings/Account/Usage.tsx`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2024-09-20 18:34 UTC, kien-ngo commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4727?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4727** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4727?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4722** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4722?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-21 01:57 UTC, jnsdls requested changes

2024-09-21 01:57 UTC, jnsdls commented on apps/dashboard/src/components/hackathon/HackathonFooter.tsx
> +    <div className="flex flex-col items-center bg-[url('/assets/hackathon/footer-bg.png')] bg-cover bg-no-repeat bg-center w-full py-20 space-y-10 rounded-t-[50px] px-6">
prefer `gap` over `space`

2024-09-21 01:57 UTC, jnsdls commented on apps/dashboard/src/components/hackathon/Judges.tsx
> +    <div className="space-y-8 relative flex flex-col">
gap over space

2024-09-21 01:57 UTC, jnsdls commented on apps/dashboard/src/components/hackathon/JudgesEarn.tsx
> +    <div className="flex flex-col space-y-8 relative">
gap

2024-09-21 01:57 UTC, jnsdls commented on apps/dashboard/src/components/hackathon/common/AvatarShowcase.tsx
> +    <div className="flex flex-col spacing-y-12">
mind the gap

2024-09-21 01:57 UTC, jnsdls commented on apps/dashboard/src/components/onboarding/Steps.tsx
> +        className={`gap-2 flex flex-col items-start p-6 ${rightImageDark && !isMobile ? "w-[60%]" : "w-full"}`}
use `cn()` util for optional classes

2024-09-21 01:57 UTC, jnsdls commented on apps/dashboard/src/components/settings/Account/AccountForm.tsx
> +        className={`items-start w-full ${horizontal ? "gap-6" : "gap-8"} rounded-xl ${padded ? "border border-border p-6" : "p-0"} bg-background`}
`cn()` for conditionals

2024-09-22 11:52 UTC, closed without merging