Replace JS and TS icons
thirdweb-dev/js pull request #4812
Opened 2024-09-26 12:43 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-09-26 12:43 UTC, kien-ngo commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4812?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4812** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4812?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4811** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4811?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4810** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4810?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-26 13:47 UTC, MananTank commented on apps/dashboard/src/components/icons/brand-icons/JavaScriptIcon.tsx
> +  );
Name the component - JavaScriptIcon instead

2024-09-26 13:48 UTC, MananTank commented on apps/dashboard/src/components/icons/brand-icons/TypeScriptIcon.tsx
> +};
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line +19]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->Name the component TypeScriptIcon instead<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4812?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-09-26 13:48 UTC, MananTank requested changes
address comments

2024-09-27 01:11 UTC, MananTank approved these changes

2024-09-27 01:35 UTC, merged