[Dashboard] Replace React icon
thirdweb-dev/js pull request #4813
Opened 2024-09-26 13:06 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

---

## PR-Codex overview
This PR focuses on replacing the usage of the `SiReact` icon with a newly created `ReactIcon` component across multiple files in the `dashboard` application, enhancing consistency and maintainability.

### Detailed summary
- Added `ReactIcon` component in `apps/dashboard/src/components/icons/brand-icons/ReactIcon.tsx`.
- Replaced `SiReact` with `ReactIcon` in:
  - `ConnectSDKCard.tsx`
  - `ConnectPlaygroundButton.tsx`
  - `CodeOptionButton.tsx`
  - `SupportedPlatformLink.tsx`
  - `CodeSegment.tsx`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2024-09-26 13:07 UTC, kien-ngo commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4813?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4813** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4813?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4812** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4812?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4811** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4811?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4810** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4810?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-26 13:46 UTC, MananTank commented on apps/dashboard/src/components/icons/brand-icons/ReactIcon.tsx
> +export const React = (props: SVGProps<SVGSVGElement>) => {
name the component as ReactIcon instead of React

2024-09-26 13:46 UTC, MananTank requested changes
name the component as ReactIcon

2024-09-27 01:12 UTC, MananTank approved these changes

2024-09-27 01:36 UTC, merged