[Dashboard] Remove <Stack/> (5)
thirdweb-dev/js pull request #4844
Opened 2024-09-28 19:53 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-09-28 19:54 UTC, kien-ngo commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4844?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4844** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4844?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4843** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4843?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-29 18:29 UTC, jnsdls requested changes

2024-09-29 18:29 UTC, jnsdls commented on apps/dashboard/src/components/contract-components/contract-publish-form/landing-fieldset.tsx
> +            extraClass="w-full"
can this just be `className`?

2024-09-30 00:01 UTC, jnsdls requested changes

2024-09-30 00:01 UTC, jnsdls commented on apps/dashboard/src/core-ui/batch-upload/lazy-mint-form/select-option.tsx
> +          disabled ? "cursor-not-allowed" : "cursor-pointer",
combine these, it's the same condition

2024-09-30 00:01 UTC, jnsdls commented on apps/dashboard/src/core-ui/batch-upload/lazy-mint-form/select-option.tsx
> +          className || "",
no need for `|| ""`

2024-09-30 21:44 UTC, jnsdls approved these changes

2024-09-30 23:44 UTC, merged