[Dashboard] Remove ListItem (1) and fix some UI issues from the aspect-ratio PR
thirdweb-dev/js pull request #4846
Opened 2024-09-29 21:34 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-09-29 21:35 UTC, kien-ngo commented
* **#4846** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4846?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-30 00:04 UTC, jnsdls requested changes

2024-09-30 00:04 UTC, jnsdls commented on apps/dashboard/src/contract-ui/tabs/listings/components/list-form.tsx
> +  Card,
do not add new imports from `tw-components` - we are removing this, there should be a `card` component in shadcn components we already use

2024-09-30 00:04 UTC, jnsdls commented on apps/dashboard/src/contract-ui/tabs/nfts/components/airdrop-upload.tsx
> +import { Upload } from "lucide-react";
`UploadIcon`

2024-09-30 15:50 UTC, MananTank commented on apps/dashboard/src/pages/hackathon/earn.tsx
>                    <List color="white" styleType="none" maxW={807} spacing={3}>
<List> not removed

2024-09-30 15:50 UTC, MananTank commented on apps/dashboard/src/pages/hackathon/earn.tsx
>                    <List color="white" styleType="none" spacing={3}>
<List> not removed

2024-09-30 15:50 UTC, MananTank commented on apps/dashboard/src/pages/hackathon/consumer-crypto.tsx
>                    <List>
<List> not removed

2024-09-30 15:53 UTC, MananTank requested changes
The bullet icon is going outside the list container a little bit - Prefer using `<UnorderedList />` or `<OrderedList />` component ( defined in components/ui/List.tsx ) with `<li />` instead

2024-09-30 19:03 UTC, jnsdls reviewed
just waiting for manan's feedback to be addressed

2024-09-30 21:08 UTC, jnsdls reviewed
LG from my side - will wait for @MananTank to sign off

2024-09-30 21:17 UTC, MananTank approved these changes

2024-09-30 22:47 UTC, merged