Add ecosystem wallet security documentation
thirdweb-dev/js pull request #4911
Opened 2024-10-03 16:01 UTC by ianthirdweb

## Problem solved

Short description of the bug fixed or feature added

2024-10-03 16:05 UTC, MananTank commented on apps/portal/src/app/connect/sidebar.tsx
> +<<<<<<< Updated upstream
Merge conflict marker is commited

2024-10-03 16:05 UTC, MananTank requested changes
Remove merge conflict markers and fix conflict

2024-10-04 19:28 UTC, joaquim-verges commented on apps/portal/src/app/connect/ecosystems/security/page.mdx
> +- Applications can [link multiple authentication methods](/link-multiple-profiles) to the same enclave. Any of these methods can be used to authenticate into the users wallet.
```suggestion
- Applications can [link multiple authentication methods](/connect/in-app-wallet/guides/link-multiple-profiles) to the same enclave. Any of these methods can be used to authenticate into the users wallet.
```

2024-10-04 19:28 UTC, joaquim-verges commented on apps/portal/src/app/connect/ecosystems/security/page.mdx
> +  - We replaced the SSS model tricky with Encalves because a malicious developer could reverse engineer and extract the private key from the client and exploit users who might’ve assets from other de
```suggestion
  - We moved away from the shamir secret sharing model and replaced it with Encalves. This ensures no-one can extract the private key from the client, including other developers in the ecosystem.
```

2024-10-04 19:28 UTC, joaquim-verges commented on apps/portal/src/app/connect/ecosystems/security/page.mdx
> +  - With enclave and partner policies, this is mitigated. Ecosystem owners are able to place restrictions on what individual partners are able to do. Moreover, since the private key is never re-const
```suggestion
  - With enclave and partner policies, ecosystem owners are able to place restrictions on what individual partners are able to do. Since the private key is never re-constructed on the client, the ecosystem partner must submit the request to the enclave which would be able to verify the request and block requests that are out of scope or denied by the ecosystem owner.
```

2024-10-04 19:28 UTC, joaquim-verges commented on apps/portal/src/app/connect/ecosystems/security/page.mdx
> +  3.  If application providers **do not have direct access** to user accounts or private keys, as these remain secured within the enclave. The enclave's design ensures that only verified user request
```suggestion
  3.  Application providers **do not have direct access** to user accounts or private keys, as these remain secured within the enclave. The enclave's design ensures that only verified user requests can trigger wallet operations.
```

2024-10-04 19:28 UTC, joaquim-verges commented on apps/portal/src/app/connect/ecosystems/security/page.mdx
> +- The enclave provides a verifiable hash of the image of the code that is being run on the device, allowing anyone to verify the contents of the code for malicious intent.
```suggestion
- The enclave provides a verifiable hash of the image of the code that is being run on the device, allowing anyone to verify the contents of the code.
```

2024-10-04 19:28 UTC, joaquim-verges commented on apps/portal/src/app/connect/ecosystems/security/page.mdx
> +- All sensitive operations, such as transaction signing, occur within the enclave, further protecting the wallet's security.
```suggestion
- All sensitive operations, such as transaction signing, occur within the enclave, ensuring the wallet's security.
```

2024-10-04 19:53 UTC, merged