[Dashboard] Replace erc721 claim Drawer with Sheet
thirdweb-dev/js pull request #4932
Opened 2024-10-06 04:42 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-10-06 04:42 UTC, kien-ngo commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4932?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4932** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4932?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4931** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4931?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-07 14:02 UTC, MananTank commented on apps/dashboard/src/contract-ui/tabs/nfts/components/claim-button.tsx
> +              const approveTx = await getApprovalForTransaction({
This can throw error - it should be wrapped in try-catch ( as it was earlier ) -wrap the entire submit handler with try catch

2024-10-07 14:02 UTC, MananTank requested changes
address comments

2024-10-08 16:37 UTC, MananTank approved these changes

2024-10-08 17:12 UTC, merged