Add Unlimited wallets Banner, Add Team & Legacy dashboard links in headers
thirdweb-dev/js pull request #4971
Opened 2024-10-09 16:19 UTC by MananTank

## Problem solved

Short description of the bug fixed or feature added

2024-10-09 16:19 UTC, MananTank commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4971?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4971** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4971?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4968** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4968?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4967** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4967?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-09 16:54 UTC, jnsdls approved these changes

2024-10-09 17:08 UTC, jnsdls requested changes
blocking so we don't accidentally merge early

2024-10-10 18:33 UTC, jnsdls approved these changes

2024-10-10 18:55 UTC, merged