[Dashboard] Mobile menu drawer -> Sheet
thirdweb-dev/js pull request #4999
Opened 2024-10-11 23:14 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-10-11 23:14 UTC, kien-ngo commented
* **#4999** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4999?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-14 15:24 UTC, MananTank reviewed
Let's make a few adjustments to UI while we are making changes here

1. Increase the icon size ( its currently 16x16 ) - lets change make it size-6

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/yNOf1svJ8o3zjO7zQouZ/ce0aa0a9-dc2d-4930-945a-216a9652e567.png)

2. Let's add a py-2 on all the links so its easier to click on them. ( lets also make sure the sheet has overflow auto )

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/yNOf1svJ8o3zjO7zQouZ/54e89ec4-f1a3-4e6e-be5a-d593cbd2b470.png)

2024-10-14 15:24 UTC, MananTank requested changes
please address comments

2024-10-15 02:41 UTC, jnsdls approved these changes

2024-10-15 02:45 UTC, merged