[Dashboard] Remove react-icons (3)
thirdweb-dev/js pull request #5007
Opened 2024-10-14 05:05 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-10-14 05:05 UTC, kien-ngo commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5007?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5007** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5007?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#5006** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5006?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5005** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5005?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4999** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4999?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-14 15:29 UTC, MananTank commented on apps/dashboard/src/components/engine/contract-subscription/contract-subscriptions-table.tsx
> +        <InfoIcon />
Need to add a size className here

2024-10-14 15:30 UTC, MananTank requested changes
please address comments

2024-10-15 01:55 UTC, jnsdls approved these changes

2024-10-15 02:48 UTC, merged