[Dashboard] Marketplace Listing drawer -> Sheet
thirdweb-dev/js pull request #5008
Opened 2024-10-14 08:11 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-10-14 08:11 UTC, kien-ngo commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5008?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5008** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5008?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#5007** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5007?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5006** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5006?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5005** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5005?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4999** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4999?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-14 15:35 UTC, MananTank commented on apps/dashboard/src/contract-ui/tabs/shared-components/listing-drawer.tsx
> +      <SheetContent className="flex w-full flex-col gap-6 px-2 py-6 md:min-w-[600px]">
The `px-2` is very little padding - lets remove this

2024-10-14 15:35 UTC, MananTank requested changes
please address comments

2024-10-15 01:55 UTC, jnsdls approved these changes

2024-10-15 02:52 UTC, merged