[Service Utils] Feature: add ecosystem headers to extractAuthorizationData
thirdweb-dev/js pull request #5083
Opened 2024-10-18 17:21 UTC by gregfromstl

## Problem solved

Short description of the bug fixed or feature added

2024-10-18 18:03 UTC, jnsdls requested changes

2024-10-18 18:03 UTC, jnsdls commented on packages/service-utils/src/cf-worker/index.ts
> +    requestUrl.searchParams.get("ecosystemPartnerId");
why different pattern than above?

2024-10-22 05:58 UTC, gregfromstl commented on packages/service-utils/src/cf-worker/index.ts
> +    requestUrl.searchParams.get("ecosystemPartnerId");
Because lets are evil

2024-10-22 20:24 UTC, joaquim-verges approved these changes

2024-10-22 20:25 UTC, gregfromstl commented
### Merge activity

* **Oct 22, 4:25 PM EDT**: The merge label 'merge-queue' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=thirdweb-dev&repo=js) once it meets the requirements.

2024-10-22 21:35 UTC, merged