Add noUncheckedIndexedAccess: true in dashboard tsconfig and fix all issues
thirdweb-dev/js pull request #5084
Opened 2024-10-18 19:52 UTC by MananTank

## Problem solved

Short description of the bug fixed or feature added

2024-10-18 19:52 UTC, MananTank commented
* **#5084** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5084?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-18 21:51 UTC, jnsdls requested changes

2024-10-18 21:51 UTC, jnsdls commented on apps/dashboard/src/@/components/ui/input-otp.tsx
> +  // biome-ignore lint/style/noNonNullAssertion: <explanation>
please add the actual explanation here

2024-10-18 23:56 UTC, MananTank commented on apps/dashboard/src/@/components/ui/input-otp.tsx
> +  // biome-ignore lint/style/noNonNullAssertion: <explanation>
added

2024-10-19 02:46 UTC, jnsdls approved these changes

2024-10-19 02:56 UTC, merged