[SDK] Options to custonize ViewAssets's tabs
thirdweb-dev/js pull request #5126
Opened 2024-10-22 12:17 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

---

## PR-Codex overview
This PR introduces a feature to customize the display order of asset tabs in the `ConnectButton` component, allowing users to prioritize "NFTs" or "Tokens". It also includes updates to related components and documentation.

### Detailed summary
- Added support for customizable asset tab order in `ConnectButton`.
- Updated `ViewAssets` to dynamically set active tab based on `assetTabs` prop.
- Enhanced documentation with instructions for tab customization.
- Modified `DetailsModal` to hide the "View Funds" button if `assetTabs` is an empty array.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2024-10-22 12:17 UTC, kien-ngo commented
* **#5126** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5126?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-22 21:10 UTC, gregfromstl requested changes
I don't think we should make this change. It's incredibly niche and if they want this level of customization they should probably be building their own UI. It'll also break as soon as we add another tab to this screen.

2024-10-22 22:28 UTC, joaquim-verges commented on packages/thirdweb/src/react/core/hooks/connection/ConnectButtonProps.ts
> +  swapAssetTabsPositions?: boolean;
if we're gonna do this, the api should be an array, and the array order is what drives the ui

like:

```
assetTabs: ["tokens", "nfts"]
```

and if passing empty array, we don't show the button at all

2024-10-29 09:40 UTC, kien-ngo commented
We were having a discussion here: https://linear.app/thirdweb/issue/CNCT-2036/feedbackfeature-request-on-nfts-tab
Joaquim thought it would be a good idea to add this feature

2024-11-01 18:03 UTC, gregfromstl approved these changes

2024-11-01 18:06 UTC, gregfromstl commented
### Merge activity

* **Nov 1, 2:06 PM EDT**: The merge label 'merge-queue' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=thirdweb-dev&repo=js) once it meets the requirements.

2024-11-01 18:36 UTC, merged