Chain Page Verification for Shido Network
thirdweb-dev/js pull request #5279
Opened 2024-11-04 15:26 UTC by DustinTurska

## Problem solved

Short description of the bug fixed or feature added

2024-11-04 16:05 UTC, gregfromstl requested changes

2024-11-04 16:05 UTC, gregfromstl commented on apps/dashboard/src/app/(dashboard)/(chain)/utils.ts
> +      "Shido Network is a superfast EVM chain with the lowest fees. Seamlessly interoperable with the the Cosmos, EVM and WASM. Bringing you the future of DeFi, unlocking unified liquidity through ch
Typo in here "the the"

2024-11-04 16:33 UTC, DustinTurska commented on apps/dashboard/src/app/(dashboard)/(chain)/utils.ts
> +      "Shido Network is a superfast EVM chain with the lowest fees. Seamlessly interoperable with the the Cosmos, EVM and WASM. Bringing you the future of DeFi, unlocking unified liquidity through ch
Good catch, pushing update now

2024-11-12 20:45 UTC, gregfromstl approved these changes

2024-11-12 22:00 UTC, jnsdls approved these changes

2024-11-13 18:32 UTC, gregfromstl commented
### Merge activity

* **Nov 13, 1:32 PM EST**: The merge label 'merge-queue' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=thirdweb-dev&repo=js) once it meets the requirements.

2024-11-26 01:52 UTC, merged