Send UTM params when logging into dashboard
thirdweb-dev/js pull request #5400
Opened 2024-11-12 21:39 UTC by MananTank

## Problem solved

Short description of the bug fixed or feature added

2024-11-12 21:40 UTC, MananTank commented
* **#5400** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5400?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-13 01:29 UTC, jnsdls requested changes

2024-11-13 01:29 UTC, jnsdls commented on apps/dashboard/src/middleware.ts
> +        }
is this accurate?

2024-11-13 01:29 UTC, jnsdls commented on apps/dashboard/src/middleware.ts
> +    const searchParamsEntires = request.nextUrl.searchParams.entries();
pls address

2024-11-13 01:35 UTC, MananTank commented on apps/dashboard/src/middleware.ts
> +    const searchParamsEntires = request.nextUrl.searchParams.entries();
fixed

2024-11-13 01:36 UTC, MananTank commented on apps/dashboard/src/middleware.ts
> +        }
completely changed how this works - this is no longer relevant now

2024-11-13 01:37 UTC, jnsdls commented on apps/dashboard/src/middleware.ts
> +  // NOTE: this is not working for pages with rewrites in next.config.js - (framer pages)
I wonder if we should just move all the rewrites into the middleware instead of doing it "in front" of middleware?

2024-11-22 07:46 UTC, jnsdls approved these changes

2024-11-22 08:17 UTC, merged