Updated Mintable Modules
thirdweb-dev/js pull request #5404
Opened 2024-11-12 23:00 UTC by GWSzeto

- mintWithRole now passes in empty string if the nft passed in is the empty string

## Problem solved

Short description of the bug fixed or feature added

2024-11-13 18:27 UTC, gregfromstl commented
@GWSzeto is there an eng linear ticket for this? The one linked is under design and marked as completed. Sorry for being strict about this it just helps give context so we can review

2024-11-13 20:34 UTC, MananTank commented on packages/thirdweb/src/extensions/modules/MintableERC1155/mintWithRole.ts
> +      console.log("tokenId: ", tokenId);
remove this log

2024-11-13 20:35 UTC, MananTank requested changes
please address comments

2024-11-13 20:57 UTC, GWSzeto commented on apps/dashboard/src/app/(dashboard)/(chain)/[chain_id]/[contractAddress]/modules/components/Mintable.tsx
> +          params: [ownerAccount.address, MINTER_ROLE],
Updated to use the extension

2024-11-14 17:48 UTC, MananTank approved these changes

2024-11-19 18:16 UTC, gregfromstl approved these changes

2024-11-19 18:30 UTC, GWSzeto commented
### Merge activity

* **Nov 19, 1:30 PM EST**: The merge label 'merge-queue' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=thirdweb-dev&repo=js) once it meets the requirements.
* **Nov 19, 1:30 PM EST**: A user added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=thirdweb-dev&repo=js).

2024-11-19 18:35 UTC, merged