Add account settings page with Name and Email fields
thirdweb-dev/js pull request #5461
Opened 2024-11-19 20:42 UTC by MananTank

## Problem solved

Short description of the bug fixed or feature added

2024-11-19 20:42 UTC, MananTank commented
* **#5461** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5461?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5461?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-20 18:12 UTC, jnsdls commented on apps/dashboard/src/app/account/settings/AccountSettingsPage.tsx
> +          // to send OTP to email, we use updateAccount
agreed weird - but it is what it is for right now

2024-11-20 18:14 UTC, jnsdls requested changes
needs to handle errors from API server when trying to update to an email that another account already has set - api call fails but generic RSC error shows to user

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/VXaCVgbx1DROqoQd8UuD/afc63395-7d89-4fd0-902c-53d923cb82d3.png)

also should now allow updating to proceed if the email entered is the same as the currently verified email

2024-11-20 20:54 UTC, jnsdls approved these changes

2024-11-20 21:05 UTC, merged