feat: Select Engine versions
thirdweb-dev/js pull request #5479
Opened 2024-11-21 09:35 UTC by arcoraven

https://linear.app/thirdweb/issue/INFRA-401/update-multiple-engine-versions

<img width="480" alt="image" src="https://github.com/user-attachments/assets/7637580e-512c-4d6a-b414-5f54f6c0cb31">

<img width="480" alt="image" src="https://github.com/user-attachments/assets/7dd1b6d0-51fb-405e-ab67-4f2465e8a084">

---

## PR-Codex overview
This PR primarily refactors the handling of `teamSlug` across various components and introduces new functionalities related to deployment public configuration and version updates.

### Detailed summary
- Renamed `team_slug` to `teamSlug` in multiple components.
- Added `useEngineGetDeploymentPublicConfiguration` hook for fetching deployment config.
- Updated `EngineVersionBadge` and `ChangeVersionModal` to accommodate new version update logic and alerts.
- Modified the update process to include team-specific deployment paths.
- Enhanced user interface with alerts and new selection options for version updates.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2024-11-22 08:33 UTC, MananTank commented on apps/dashboard/src/app/team/[team_slug]/(team)/~/engine/(instance)/[engineId]/_components/EnginePageLayout.tsx
> +        <EngineVersionBadge instance={instance} teamId={instance.accountId} />
Please use `team.id` here

2024-11-22 08:36 UTC, MananTank requested changes
please address comments

2024-11-22 08:40 UTC, MananTank commented on apps/dashboard/src/app/team/[team_slug]/(team)/~/engine/(instance)/[engineId]/_components/version.tsx
> +    publicConfigurationQuery.data.serverVersions?.length === 0
Build is failing. Type issue: 
https://vercel.com/thirdweb/thirdweb-www/C2i1x6cZEVJuKfQSe6uz45NXdhnv?filter=errors

2024-11-25 11:17 UTC, MananTank approved these changes

2024-11-25 12:53 UTC, arcoraven commented
### Merge activity

* **Nov 25, 7:53 AM EST**: The merge label 'merge-queue' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=thirdweb-dev&repo=js) once it meets the requirements.
* **Nov 25, 7:53 AM EST**: A user added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=thirdweb-dev&repo=js).

2024-11-25 12:54 UTC, merged