add roleBytes utility for contract role usage
thirdweb-dev/js pull request #5685
Opened 2024-12-10 22:25 UTC by dirtycajunrice

## Problem solved

Short description of the bug fixed or feature added

2024-12-10 22:26 UTC, dirtycajunrice commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5685?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5685** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5685?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5685?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#5683** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5683?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-11 00:42 UTC, joaquim-verges reviewed
can you add a changeset for this one?

pnpm changeset from the root of the repo - make it a patch

2024-12-11 00:43 UTC, joaquim-verges commented on packages/thirdweb/src/utils/encoding/helpers/role-bytes.ts
> +export const roleBytes = (role: string): `0x${string}` => {
need to export it publicly, you can do that by exporting it from /exports

likely under /exports/extensions/common.ts where the other role stuff is

2024-12-11 00:45 UTC, joaquim-verges commented on packages/thirdweb/src/utils/encoding/helpers/role-bytes.ts
> + * @param {string} role - The role string to be converted into bytes and hashed.
how about a union type for this of 'known' role strings + | ({} & string) to allow for others:
```
type KnownRoles = "ADMIN_ROLE" | "MINTER_ROLE" ...
type Role = KnownRoles | ({} & string)
```

2024-12-12 19:31 UTC, joaquim-verges requested changes
ugh, just realized we already have a `getRoleHash` function that's already exported and does the same thing

2024-12-20 23:27 UTC, dirtycajunrice commented
> ugh, just realized we already have a `getRoleHash` function that's already exported and does the same thing
Thats great. Ill close this then.

2024-12-20 23:28 UTC, closed without merging