[SDK] Test coverage
thirdweb-dev/js pull request #5851
Opened 2024-12-29 08:19 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-12-29 08:19 UTC, kien-ngo commented
* **#5851** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5851?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5851?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/thirdweb-dev?ref=merge-queue-instructions-in-stack-comment&prId=5851).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-02 08:30 UTC, gregfromstl requested changes

2025-01-02 08:30 UTC, gregfromstl commented on packages/thirdweb/src/extensions/marketplace/direct-listings/direct-listings.test.ts
> +import { toFunctionSelector } from "viem";
Use Ox for this

2025-01-02 14:07 UTC, kien-ngo commented on packages/thirdweb/src/extensions/marketplace/direct-listings/direct-listings.test.ts
> +import { toFunctionSelector } from "viem";
@gregfromstl toFunctionSelector only exists in viem. I dont think there's an equivalence in Ox

2025-01-03 01:07 UTC, jxom commented on packages/thirdweb/src/extensions/marketplace/direct-listings/direct-listings.test.ts
> +import { toFunctionSelector } from "viem";
https://oxlib.sh/api/AbiFunction/getSelector

2025-01-03 07:10 UTC, kien-ngo commented on packages/thirdweb/src/extensions/marketplace/direct-listings/direct-listings.test.ts
> +import { toFunctionSelector } from "viem";
awesome ser ty

2025-01-13 02:01 UTC, closed without merging