update
thirdweb-dev/js pull request #5860
Opened 2024-12-31 03:39 UTC by kien-ngo

## Problem solved

Short description of the bug fixed or feature added

2024-12-31 03:40 UTC, kien-ngo commented
* **#5860** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5860?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/5860?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/thirdweb-dev?ref=merge-queue-instructions-in-stack-comment&prId=5860).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-01 11:04 UTC, MananTank commented on apps/dashboard/src/app/(dashboard)/(chain)/[chain_id]/[contractAddress]/nfts/components/claim-button.tsx
> +                  to: d.to.trim(),
whitespace is ignored during validation, so it may or may not have whitespace - but its not removed when passing to `claimTo`. 

Always save the trimmed value instead:

```
onChange: (e) => {
 form.setValue('to', e.target.value.trim(), { shouldValidate: true });
}
```

2025-01-01 11:04 UTC, MananTank requested changes
please address comments

2025-01-03 08:07 UTC, kien-ngo commented on apps/dashboard/src/app/(dashboard)/(chain)/[chain_id]/[contractAddress]/nfts/components/claim-button.tsx
> +                  to: d.to.trim(),
updated thanks for the review

2025-01-03 22:36 UTC, gregfromstl approved these changes

2025-01-03 22:44 UTC, merged