update the params for type of contracts
thirdweb-dev/js pull request #712
Opened 2023-03-11 14:35 UTC by atharvadeosthale

Hooks `useUnclaimedNFTs()`, `useClaimedNFTs()`, `useUnclaimedNFTSupply()`, and `useClaimedNFTSupply()` don't work with edition drop contracts, however, the comments on these hooks specified they could.

2023-03-11 18:45 UTC, nachoiacovino requested changes
we can't accept only NFTDrop which is the prebuilt, we need to accept DropContract (that has all drops) but exclude all erc1155 and erc20, so find how we do it elsewhere, but need to do a DropContract exclude EditionDrop, TokenDrop

2023-03-11 20:36 UTC, atharvadeosthale commented
`useClaimedNFTs` and `useUnclaimedNFTs` took only `NFTDrop` even before so I changed their link to point to `NFTDrop`. For the ones where we exclude edition drop and token drop I've added normal text and removed links

2023-03-13 17:56 UTC, nachoiacovino commented on packages/react-core/src/evm/hooks/async/drop.ts
> + * @param contract - an instance of a {@link NFTDrop}
this is not correct now

2023-03-13 17:57 UTC, nachoiacovino requested changes
fix the params plz :D

2023-03-13 19:19 UTC, nachoiacovino approved these changes
lgtm!

2023-03-13 19:42 UTC, merged