Add detect-project command to CLI
thirdweb-dev/js pull request #926
Opened 2023-04-21 17:37 UTC by Marfuen

2023-04-28 18:13 UTC, jnsdls requested changes
add a changeset please `pnpm changeset` at the root

2023-04-28 18:59 UTC, jnsdls commented
/release-pr

2023-04-28 22:00 UTC, Marfuen commented
@jnsdls I pushed another change, so we need to remake the dev build

2023-04-28 22:28 UTC, Marfuen commented
/release-pr

2023-04-28 22:32 UTC, Marfuen commented
/release-pr

2023-05-02 17:02 UTC, Marfuen commented
/release-pr

2023-05-16 20:00 UTC, jnsdls approved these changes
LGTM

2023-05-16 20:12 UTC, merged